name: ci

on: pull_request

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.17.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vet
        uses: golangci/golangci-lint-action@v2
        run: go vet ./..
