name: ci

on: pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.17.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --issues-exit-code=0
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
